name: Software composition analysis (SCA)

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  Build_Publish_Stage:
    runs-on: ubuntu-latest
    name: Build, Publish, and Stage
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install CycloneDX Python module
      run: |
        pip install cyclonedx-bom
    - name: Create BOM
      run: |
        cyclonedx-py -r -i requirements.txt -o bom.xml

    - name: Upload BOM to Dependency-Track
      run: |
        curl -v -X "POST" "${{ secrets.DTRACK_API_ENDPOINT }}" \
             -H 'Content-Type: multipart/form-data' \
             -H 'X-API-Key: ${{ secrets.DTRACKAPIKEY }}' \
             -F 'project=${{ secrets.DTRACKPROJID }}' \
             -F 'projectname=python-sample-vscode-flask-tutorial' \
             -F 'bom=@${{ github.workspace }}/bom.xml'
      continue-on-error: true
